# Generated by Django 2.2.4 on 2019-08-13 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('place', models.TextField()),
                ('address', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_virtual', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('CONFERENCE', 'Conference'), ('SEMINAR', 'Seminar'), ('CONGRESS', 'Congress'), ('COURSE', 'Course')], default=events_app.models.EventCategories('Conference'), max_length=10)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
